# Generated by Django 4.1.7 on 2023-03-24 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=500)),
                ('txid', models.CharField(max_length=500)),
                ('pay', models.CharField(max_length=500)),
                ('per', models.CharField(max_length=500)),
                ('skill', models.CharField(max_length=500)),
                ('portfolio', models.CharField(max_length=500)),
                ('available', models.CharField(max_length=500)),
                ('bio', models.TextField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
